/**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import type * as Types from '../../api.schema';

import { api } from '../../..';
export type ServicesQueryVariables = Types.Exact<{
  providerId?: Types.InputMaybe<Types.Scalars['Int']>;
  limit?: Types.InputMaybe<Types.Scalars['Int']>;
  cursor?: Types.InputMaybe<Types.Scalars['Int']>;
  page?: Types.InputMaybe<Types.Scalars['Int']>;
  paginationType?: Types.InputMaybe<Types.PaginationType>;
}>;


export type ServicesQueryResult = { __typename?: 'Query', services?: { __typename?: 'ServicesQueryResults', cursor?: number | null, count?: number | null, services: Array<{ __typename?: 'Service', id: number, name?: string | null, description?: string | null, price?: number | null, duration?: number | null, durationUnit?: Types.DurationUnitType | null, inHouse?: boolean | null, category?: Types.CategoryType | null }> } | null };


export const ServicesDocument = `
    query services($providerId: Int, $limit: Int, $cursor: Int, $page: Int, $paginationType: PaginationType) {
  services(
    providerId: $providerId
    limit: $limit
    cursor: $cursor
    page: $page
    paginationType: $paginationType
  ) {
    services {
      id
      name
      description
      price
      duration
      durationUnit
      inHouse
      category
    }
    cursor
    count
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    services: build.query<ServicesQueryResult, ServicesQueryVariables | void>({
      query: (variables) => ({ document: ServicesDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useServicesQuery, useLazyServicesQuery } = injectedRtkApi;

