/**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import type * as Types from '../../api.schema';

import { api } from '../../..';
export type StaffsQueryVariables = Types.Exact<{
  providerId?: Types.InputMaybe<Types.Scalars['Int']>;
  limit?: Types.InputMaybe<Types.Scalars['Int']>;
  cursor?: Types.InputMaybe<Types.Scalars['Int']>;
  page?: Types.InputMaybe<Types.Scalars['Int']>;
  paginationType?: Types.InputMaybe<Types.PaginationType>;
}>;


export type StaffsQueryResult = { __typename?: 'Query', staffs?: { __typename?: 'StaffsQueryResults', cursor?: number | null, count?: number | null, staffs: Array<{ __typename?: 'Staff', id: number, firstName?: string | null, lastName?: string | null }> } | null };


export const StaffsDocument = `
    query staffs($providerId: Int, $limit: Int, $cursor: Int, $page: Int, $paginationType: PaginationType) {
  staffs(
    providerId: $providerId
    limit: $limit
    cursor: $cursor
    page: $page
    paginationType: $paginationType
  ) {
    staffs {
      id
      firstName
      lastName
    }
    cursor
    count
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    staffs: build.query<StaffsQueryResult, StaffsQueryVariables | void>({
      query: (variables) => ({ document: StaffsDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useStaffsQuery, useLazyStaffsQuery } = injectedRtkApi;

