/**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import type * as Types from '../../api.schema';

import { api } from '../../..';
export type OperatingTimeQueryVariables = Types.Exact<{
  operatingTimeId: Types.Scalars['Int'];
}>;


export type OperatingTimeQueryResult = { __typename?: 'Query', operatingTime: { __typename?: 'OperatingTime', id: number, day?: Types.DayType | null, opens?: string | null, closes?: string | null } };


export const OperatingTimeDocument = `
    query operatingTime($operatingTimeId: Int!) {
  operatingTime(operatingTimeId: $operatingTimeId) {
    id
    day
    opens
    closes
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    operatingTime: build.query<OperatingTimeQueryResult, OperatingTimeQueryVariables>({
      query: (variables) => ({ document: OperatingTimeDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useOperatingTimeQuery, useLazyOperatingTimeQuery } = injectedRtkApi;

