query providers($search: String) {
  providers(search: $search) {
    id
    tradingName
    phone
    logoUrl
    addresses {
      id
      streetNumber
      streetName
      town
      city
      province
      areaCode
    }
    operatingTimes {
      id
      day
      opens
      closes
    }
    socials {
      id
      name
      username
    }
    staffs {
      id
      firstName
      lastName
    }
  }
}
