/**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import type * as Types from '../../api.schema';

import { api } from '../../..';
export type GalleryQueryVariables = Types.Exact<{
  galleryId: Types.Scalars['Int'];
}>;


export type GalleryQueryResult = { __typename?: 'Query', gallery: { __typename?: 'Gallery', id: number, name?: string | null, galleryImageUrl?: string | null } };


export const GalleryDocument = `
    query gallery($galleryId: Int!) {
  gallery(galleryId: $galleryId) {
    id
    name
    galleryImageUrl
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    gallery: build.query<GalleryQueryResult, GalleryQueryVariables>({
      query: (variables) => ({ document: GalleryDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useGalleryQuery, useLazyGalleryQuery } = injectedRtkApi;

